export default {
  HOME: 'HOME',
  CHAIRMAN: 'chairman',
  // HOMEOWNER: 'पारिवारिक विवरण थप',
  DRAWER: 'DRAWER',
  PARICHAYA: 'परिचय',
  WADAPRATINIDHI: 'वडा जनप्रतिनिधिहरु',
  KARMACHARI: 'कर्मचारीहरु',
  TOLE: 'टोलहरु',
  GHARBIBARAN: 'घरको विवरण',
  GHARSAMMANDHIBIBARAN: 'घर सम्बन्धी विवरण',
  PARIBARBIBARAN: 'पारिवारिक विवरण',
  PARIBARSAMBANDHIBIBARAN: 'पारिवारिक विवरण थप',
  SANGSANSTHA: 'संघ संस्थाहरु',
  SROTSADHAN: 'स्रोत साधनहरु',
  GHUMNETHAU: 'घुम्नै पर्ने ठाउंहरु',
  SUCHANA: 'सूचना',
  SAMPARKA: 'सम्पर्क',
  LOGIN: 'LOGIN',
  REGISTER: 'REGISTER',
  MAPS: 'MAP',
  LAUNCH: 'NOINTERNET',
  GHRDETAIL: 'GHARBIBARANDETAIL',
  PARIBARDETAIL: 'PARIBARDETAIL',
  ROADBIBARAN: 'बाटो सम्बन्धी विवरण',
  ROAD: 'बाटोको विवरण',
  ROADDETAIL: 'ROADETAILS',
  ENDPOINT: 'ENDPOINT',
  BRIDGE: 'BRIDGE',
  BRIDGEBIBARAN: 'पुलको विवरण',
  BRIDGEDETAIL: 'BRIDGEDETAIL',
  NEWMAP: 'NEWMAP',
};
