export default {
  HOME: 'home',
  CHAIRMAN: 'chairman',
  HOMEOWNER: 'पारिवारिक विवरण थप',
  DRAWER: 'Drawer',
  PARICHAYA: 'परिचय',
  WADAPRATINIDHI: 'वडा जनप्रतिनिधिहरु',
  KARMACHARI: 'कर्मचारीहरु',
  TOLE: 'टोलहरु',
  GHARBIBARAN: 'घरको विवरण',
  GHARSAMMANDHIBIBARAN: 'घर सम्बन्धी विवरण',
  PARIBARBIBARAN: 'पारिवारिक विवरण',
  SANGSANSTHA: 'संघ संस्थाहरु',
  SROTSADHAN: 'स्रोत साधनहरु',
  GHUMNETHAU: 'घुम्नै पर्ने ठाउंहरु',
  SUCHANA: 'सूचना',
  SAMPARKA: 'सम्पर्क',
};
